[package]
name = "os_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.22"
volatile = "0.2.6"
spin = "0.5.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
build-command = ["xbuild"]

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]